### PR TITLE
Italian

### PR DESCRIPTION
**Pull request by gsobell**

### CODE REVIEW

**Comment by gsobell** [comment]
My bad, the Italian translation isn't finished, PR by mistake.
@apetresc , would you happen to know when the next release will be? I can try to do it by then, a deadline would definitely help speed things along.

**Comment by apetresc** [comment]
I don't have a fixed date, but I am hoping to put out a release next month sometime. So let's say February 14th? :)

**Comment by gsobell** [comment]
> I don't have a fixed date, but I am hoping to put out a release next month sometime. So let's say February 14th? :)

Great! I'll try to set aside time to finish it before then.

**Comment by apetresc** [comment]
Awesome! :) Looking forward to it.

**Pull request closed without merging**
